### ISSUE TITLE
Markbot says it's fine but I know it's not 

### ISSUE THREAD

**Issue by JessJodoin** [JessJodoin/bubble-popper#1]
Hey @thomasjbradley

I'm gunna bug you now lol!

Okay, so when I run bubble popper through Markbot I get all green but when I click the bubbles to pop them the transition doesn’t happen

**Comment by thomasjbradley** [comment]
I do see one typo:
https://github.com/JessJodoin/bubble-popper/blob/gh-pages/js/main.js#L22
`end` is spelled wrong.

But your code looks really good. Markbot may just be feeling annoying.

**Comment by JessJodoin** [comment]
Thanks! @thomasjbradley 
I fixed my spelling error but the bubbles still don't do the popping transition when clicked on :( I'm not sure why it's being so mean

**Comment by thomasjbradley** [comment]
My solution doesn’t have this line, so try without it:
https://github.com/JessJodoin/bubble-popper/blob/gh-pages/css/main.css#L40

**Comment by JessJodoin** [comment]
Oh! We're getting somewhere! @thomasjbradley 

the opacity transition is working now, but the width and height transitions still aren't

**Comment by thomasjbradley** [comment]
Mine only fades out, not height/width transitions.

**Comment by JessJodoin** [comment]
Oh, well then everything works great!
Thanks @thomasjbradley :shipit:
